In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
ls

 Volume in drive C has no label.
 Volume Serial Number is F248-05BE

 Directory of C:\Users\91628\Documents\Aura\aura-blood-inventory-ai

12-08-2025  15:38    <DIR>          .
12-08-2025  15:38    <DIR>          ..
12-08-2025  14:34             4,895 .gitignore
12-08-2025  15:24    <DIR>          .ipynb_checkpoints
12-08-2025  15:38            18,579 01-Data-Loading-and-EDA.ipynb
12-08-2025  14:34             1,094 LICENSE
12-08-2025  14:34               122 README.md
22-05-2023  22:23            12,843 transfusion.csv
22-05-2023  22:23             3,165 transfusion.names
               6 File(s)         40,698 bytes
               3 Dir(s)   1,519,165,440 bytes free

In [5]:
filename='transfusion.csv'

In [9]:
df_uci=pd.read_csv(filename)

In [10]:
df_uci.head()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0

In [12]:
df_uci.columns=['recency_months', 
    'frequency_times', 
    'monetary_cc_blood', 
    'time_months', 
    'donated_mar_2007']

In [14]:
df_uci.head()

,recency_months,frequency_times,monetary_cc_blood,time_months,donated_mar_2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0